name: Microservices CD

on:
  push:
    tags:
      - 'v*-pre-prod'

jobs:
  deploy-microservices-pre-prod:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        microservices: [ "api" ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.ACCESS_TOKEN }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: builder

      - name: Extract metadata (tags, labels) for Docker
        uses: docker/metadata-action@v3.7.0
        id: docker-metadata
        with:
          images: ghcr.io/${{ github.repository }}/${{ matrix.microservices }}
          tags: |
            type=raw,value=latest,enable=false
            type=raw,value=latest-pre-prod,enable=true

      - name: Build and push ${{ matrix.microservices }} Docker image
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.builder.outputs.name }}
          context: ./microservices/${{ matrix.microservices }}
          file: ./dockerfiles/${{ matrix.microservices }}-prod.Dockerfile
          tags: ${{ steps.docker-metadata.outputs.tags }}
          labels: ${{ steps.docker-metadata.outputs.labels }}
          push: true
